version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: flaskapp
      POSTGRES_PASSWORD: V3ryS#cr3t!
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
  app:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      DB_HOST: postgres
      DB_NAME: mydb
      DB_USERNAME: flaskapp
      DB_PASSWORD: V3ryS#cr3t!
volumes:
  postgres:
    driver: local
