-- MySQL Script generated by MySQL Workbench
-- sob, 20 sty 2024, 23:42:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb

-- -----------------------------------------------------
-- Table user_types
-- -----------------------------------------------------
DROP TABLE IF EXISTS user_types ;

CREATE TABLE IF NOT EXISTS user_types (
  type VARCHAR(16) NOT NULL,
  PRIMARY KEY (type));
  
-- -----------------------------------------------------
-- Table users
-- -----------------------------------------------------
DROP TABLE IF EXISTS users ;

CREATE TABLE IF NOT EXISTS users (
  login VARCHAR(64) NOT NULL,
  password TEXT NOT NULL,
  type VARCHAR(16) NOT NULL,
  picture VARCHAR NULL,
  PRIMARY KEY (login),
  CONSTRAINT fk_user_type
    FOREIGN KEY (type)
    REFERENCES user_types (type)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table clubs
-- -----------------------------------------------------
DROP TABLE IF EXISTS clubs ;

CREATE TABLE IF NOT EXISTS clubs (
  shortname VARCHAR(16) NOT NULL,
  fullname VARCHAR(64) NOT NULL,
  PRIMARY KEY (shortname));

-- -----------------------------------------------------
-- Table club_user
-- -----------------------------------------------------
DROP TABLE IF EXISTS club_user ;

CREATE TABLE IF NOT EXISTS club_user (
  user_login VARCHAR(64) NOT NULL,
  club VARCHAR(16) NOT NULL,
  PRIMARY KEY (user_login, club),
  CONSTRAINT fk_club_user
    FOREIGN KEY (user_login)
    REFERENCES users (login)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_club_club
    FOREIGN KEY (club)
    REFERENCES clubs (shortname)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table trainings
-- -----------------------------------------------------
DROP TABLE IF EXISTS trainings ;

CREATE TABLE IF NOT EXISTS trainings (
  id SERIAL,
  name VARCHAR(45) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  description VARCHAR(128) NOT NULL,
  trainer VARCHAR(64) NOT NULL,
  club VARCHAR(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_trainings_1
    FOREIGN KEY (trainer)
    REFERENCES users (login)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_trainings_2
    FOREIGN KEY (club)
    REFERENCES clubs (shortname)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table grades
-- -----------------------------------------------------
DROP TABLE IF EXISTS grades ;

CREATE TABLE IF NOT EXISTS grades (
  training_id INT NOT NULL,
  user_login VARCHAR(64) NOT NULL,
  grade INT NOT NULL,
  PRIMARY KEY (training_id, user_login),
  CONSTRAINT fk_grades_1
    FOREIGN KEY (training_id)
    REFERENCES trainings (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_grades_2
    FOREIGN KEY (user_login)
    REFERENCES users (login)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


-- -----------------------------------------------------
-- Table results
-- -----------------------------------------------------
DROP TABLE IF EXISTS results ;

CREATE TABLE IF NOT EXISTS results (
  training_id INT NOT NULL,
  user_login VARCHAR(64) NOT NULL,
  result INT NOT NULL,
  PRIMARY KEY (training_id, user_login),
  CONSTRAINT fk_results_1
    FOREIGN KEY (training_id)
    REFERENCES trainings (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_results_2
    FOREIGN KEY (user_login)
    REFERENCES users (login)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

-- -----------------------------------------------------
-- Table user_trainer
-- -----------------------------------------------------
DROP TABLE IF EXISTS user_trainer ;

CREATE TABLE IF NOT EXISTS user_trainer (
  user_login VARCHAR(64) NOT NULL,
  trainer_login VARCHAR(64) NOT NULL,
  PRIMARY KEY (user_login, trainer_login),
  CONSTRAINT fk_user_trainer_1
    FOREIGN KEY (user_login)
    REFERENCES users (login)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_user_trainer_2
    FOREIGN KEY (trainer_login)
    REFERENCES users (login)
    ON DELETE RESTRICT
    ON UPDATE CASCADE);

INSERT INTO user_types VALUES('athlete');
INSERT INTO user_types VALUES('trainer');

INSERT INTO clubs (shortname, fullname) VALUES ('football', 'Football Club');
INSERT INTO clubs (shortname, fullname) VALUES ('volleyball', 'Volleyball Club');
INSERT INTO clubs (shortname, fullname) VALUES ('track', 'Track Club');
INSERT INTO clubs (shortname, fullname) VALUES ('highjump', 'High Jump Club');
INSERT INTO clubs (shortname, fullname) VALUES ('chess', 'Chess Club');

INSERT INTO users (login, password, type) VALUES ('trainer@klubowo.pl', 'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae', 'trainer');
INSERT INTO users (login, password, type) VALUES ('athlete@klubowo.pl', 'ecd71870d1963316a97e3ac3408c9835ad8cf0f3c1bc703527c30265534f75ae', 'athlete');

INSERT INTO user_trainer VALUES ('athlete@klubowo.pl', 'trainer@klubowo.pl');